[build]
  functions = "backend/functions"
  publish = "public"  # Define the directory for static files (if you have any)

[[redirects]]
  from = "/send-code"
  to = "/.netlify/functions/sendCode"
  status = 200
  force = true

[[redirects]]
  from = "/verify-code"
  to = "/.netlify/functions/verifyCode"
  status = 200
  force = true
